version: "2"
services:
  web:
    image: nimmis/apache-php7
    ports:
      - "10080:80"
    volumes:
      - smewvolume:/var/www/html
  db:
    image: mysql:latest
    ports:
      - "13306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root2
    volumes:
      - /var/www/docker/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
    - db:db
    ports:
    - "10081:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root2
      MYSQL_ROOT_PASSWORD: root2
volumes:
  smewvolume:
    driver: rancher-nfs
