<?php

namespace AppBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('id' => 'DESC'));
	}
	public function findAllByCompany($company)
	{
		return $this->findBy(array('company'=>$company), array('id' => 'DESC'));
	}
	public function getHighestId($company)
	{
		$highest_id = $this->getEntityManager()
		->createQuery('SELECT MAX(a.manualid) FROM AppBundle:Invoice a WHERE a.company = :company')
		->setParameter('company', $company)
		->getSingleScalarResult();
		return $highest_id;
	}
}
